[package]
name = "compiler-lib"
version = "0.0.1"
authors = [
    "flip1995 <>",
    "hediet <>",
    "joshuabach <>",
    "problame <>",
    "reiner-dolp <>"
]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
failure = "0.1.3"
termcolor = "1.0.4"
derive_more = "0.13"
strum = "0.11.0"
strum_macros = "0.11.0"
memmap = "0.7.0"
libc = "*"

[dev-dependencies]
mjtest = { path = "../mjtest-rs" }
mjtest_macros = { path = "../mjtest-rs/mjtest_macros" }
