language: rust

rust:
  - nightly-2018-10-14

cache: cargo

branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # This is enabled to build pull requests.
    - master

matrix:
  include:
    - os: linux
      env: TEST_KIND="comprakt-debug"
    - os: linux
      env: TEST_KIND="comprakt-release"

    - os: linux
      env: TEST_KIND="mjtest-lexer"
    - os: linux
      env: TEST_KIND="mjtest-syntax"
    # Disable until implemented
    # - os: linux
    #   env: TEST_KIND="mjtest-ast"
    # - os: linux
    #   env: TEST_KIND="mjtest-semantic"
    # - os: linux
    #   env: TEST_KIND="mjtest-compile-firm"
    # - os: linux
    #   env: TEST_KIND="mjtest-compile"

install:
  - >
    case "$TEST_KIND" in
      comprakt-*)
        rustup component add clippy-preview && \
        rustup component add rustfmt-preview;
        break ;;
      mjtest-*)
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py --user && \
        pip install typing --user && \
        git clone https://git.scc.kit.edu/IPDSnelting/mjtest.git && \
        cd mjtest && \
        git submodule update --init && \
        git submodule update --remote && \
        cd -;
        ;;
      *)
        echo "INVALID TEST_KIND=$TEST_KIND";
        return 1;
        ;;
    esac
    

script:
  - > 
    case "$TEST_KIND" in
      comprakt-*)
        case "$TEST_KIND" in
          comprakt-release)
            FLAGS="--release"
            export RUST_MIN_STACK=$((8 * 1024 * 1024)) # 8 MiB
        esac
        cargo fmt --all -- --check && \
        cargo clippy $FLAGS --all-targets --all-features -- -D warnings && \
        cargo test $FLAGS ;
        ;;
      mjtest-*)
        MJTEST_KIND=${TEST_KIND#mjtest-}
        cargo build --release && \
        MJ_TIMEOUT=60 MJ_RUN=target/release/comprakt python3 ./mjtest/mjt.py $MJTEST_KIND ;
        ;;
      *)
        echo "INVALID TEST_KIND=$TEST_KIND"
        return 1 ;
        ;;
    esac
