language: rust

rust:
  - nightly-2018-10-14

branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # This is enabled to build pull requests.
    - master

matrix:
  include:
    - os: linux
      env: BASE_TESTS=true
    - os: osx
      env: BASE_TESTS=true
    - os: linux
      env: MJ_TESTS=lexer
    # Disable until implemented
    # - os: linux
    #   env: MJ_TESTS=syntax
    # - os: linux
    #   env: MJ_TESTS=ast
    # - os: linux
    #   env: MJ_TESTS=semantic
    # - os: linux
    #   env: MJ_TESTS=compile-firm
    # - os: linux
    #   env: MJ_TESTS=compile

install:
  - |
    if [ -z $MJ_TESTS ]; then
      rustup component add clippy-preview &&\
      rustup component add rustfmt-preview
    else
      curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py --user &&\
      pip install typing --user &&\
      git clone https://git.scc.kit.edu/IPDSnelting/mjtest.git &&\
      cd mjtest &&\
      git submodule update --init &&\
      git submodule update --remote &&\
      cd -
    fi

script:
  - |
    if [ -z $MJ_TESTS ]; then
      cargo fmt --all -- --check &&\
      cargo clippy --all-targets --all-features -- -D warnings &&\
      cargo test
    else
      cargo build --release &&\
      MJ_TIMEOUT=60 MJ_RUN=target/release/comprakt python3 ./mjtest/mjt.py $MJ_TESTS
    fi
