language: rust

rust:
  - nightly-2018-10-14

matrix:
  include:
    - os: linux
    - os: osx
    - os: windows
  allow_failures:
    - os: windows

before_script:
  - rustup component add clippy-preview
script:
  # let build fail on Clippy warnings
  # and also check tests and none-default crate features
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build
  - cargo check
