language: rust

rust:
  - nightly-2018-10-14

branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # This is enabled to build pull requests.
    - master

matrix:
  include:
    - os: linux
    - os: osx
    - os: windows
  allow_failures:
    - os: windows

before_script:
  - rustup component add clippy-preview
script:
  # let build fail on Clippy warnings
  # and also check tests and none-default crate features
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build
  - cargo check
