[package]
name = "comprakt"
version = "0.0.1"
authors = [
    "flip1995 <hello@philkrones.com>",
    "hediet <>",
    "joshuabach <>",
    "problame <>",
    "reiner-dolp <>"
]
edition = "2018"
license = "MIT OR Apache-2.0"

[workspace]
members = [ ".", "mjtest-rs", "mjtest-rs/mjtest_macros", "asciifile" ]

[dependencies]
structopt = "0.2"
failure = "0.1.3"
memmap = "0.7.0"
libc = "*"
termcolor = "1.0.4"
derive_more = "0.13"
asciifile = { path = "./asciifile" }
strum = "0.11.0"
strum_macros = "0.11.0"

[dev-dependencies]
mjtest = { path = "./mjtest-rs" }
mjtest_macros = { path = "./mjtest-rs/mjtest_macros" }
integration_test_codegen = { path = "./integration-test-codegen-rs" }
assert_cmd = "0.10"
predicates = "1.0"
difference = "2.0"
