[package]
name = "comprakt"
version = "0.0.1"
authors = [
    "flip1995 <hello@philkrones.com>",
    "hediet <>",
    "joshuabach <>",
    "problame <>",
    "reiner-dolp <>"
]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
structopt = "0.2"
failure = "0.1.3"
memmap = "0.7.0"
itertools = "0.7"
libc = "*"
termcolor = "1.0.4"
derive_more = "0.13"
