[package]
name = "comprakt"
version = "0.0.1"
authors = [
    "flip1995 <hello@philkrones.com>",
    "hediet <>",
    "joshuabach <>",
    "problame <>",
    "reiner-dolp <>"
]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
structopt = "0.2"
