[workspace]
members = [
    "asciifile",
    "compiler-lib",
    "compiler-cli",
    "inspect-ast",
    "libfirm-rs-bindings",
    "libfirm-rs",
    "mjrt",
    "symtab",
    "runner-integration-tests",
    "codegen-integration-tests"
]
exclude = [
    "mjrt-impl",
]
