#!/usr/bin/env bash
set -e

# change to this script's directory
# credits to https://stackoverflow.com/questions/4774054/reliable-way-for-a-bash-script-to-get-the-full-path-to-itself/12197518#12197518
pushd . > /dev/null
SCRIPT_PATH="${BASH_SOURCE[0]}";
while([ -h "${SCRIPT_PATH}" ]); do
    cd "`dirname "${SCRIPT_PATH}"`"
    SCRIPT_PATH="$(readlink "`basename "${SCRIPT_PATH}"`")";
done
cd "`dirname "${SCRIPT_PATH}"`" > /dev/null
SCRIPT_PATH="`pwd`";
popd  > /dev/null

TARGET="${TARGET:-release}"
COMPILER_CLI="$SCRIPT_PATH/target/$TARGET/compiler-cli"

export VANILLA=1

if [[ $BENCH == "1" ]]; then
    exec $COMPILER_CLI "$@"
else
    if [[ $# == 1 ]] ; then
        exec $COMPILER_CLI "--compile" "-O" "moderate" "$1"
    elif [[ $# == 2 ]] && [[ $1 == "--compile" ]]; then
        exec $COMPILER_CLI "--compile" "-O" "moderate" "$2"
    elif [[ $# == 2 ]] && [[ $1 == "--compile-firm" ]]; then
        exec $COMPILER_CLI "--compile-firm" "-O" "moderate" "$2"
    else
        exec $COMPILER_CLI "$@"
    fi
fi
