[package]
name = "mjrt"
version = "0.1.0"
authors = ["Christian Schwarz <me@cschwarz.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
mjrt-impl = { path = "../mjrt-impl" }
glob = "0.2"

[lib]
path = "lib.rs"
