[package]
name = "mjrt"
version = "0.1.0"
authors = ["Christian Schwarz <me@cschwarz.com>"]
edition = "2018"
links = "mjrt"
build = "build.rs"

[build-dependencies]
glob = "0.2"

[lib]
path = "lib.rs"
