libFirm: Dummy node
Dummy node
Nodes
A placeholder value.
Functions
ir_node * new_rd_Dummy (dbg_info *dbgi, ir_graph *irg, ir_mode *mode)
Construct a Dummy node.
ir_node * new_r_Dummy (ir_graph *irg, ir_mode *mode)
Construct a Dummy node.
ir_node * new_d_Dummy (dbg_info *dbgi, ir_mode *mode)
Construct a Dummy node.
ir_node * new_Dummy (ir_mode *mode)
Construct a Dummy node.
int is_Dummy (const ir_node *node)
Test if node is a Dummy.
ir_op * get_op_Dummy (void)
Returns opcode for Dummy nodes.
Variables
ir_op * op_Dummy
Dummy opcode.
Detailed Description
A placeholder value.
This is used when constructing cyclic graphs where you have cases where not all predecessors of a phi-node are known. Dummy nodes are used for the unknown predecessors and replaced later.
Function Documentation
ir_op* get_op_Dummy (void)
Returns opcode for Dummy nodes.
Definition at line 1120 of file gen_irnode.c.
References op_Dummy.
int is_Dummy (const ir_node * node)
Test if node is a Dummy.
Returns
1 if the node is a Dummy node, 0 otherwise
Definition at line 3180 of file gen_irnode.c.
ir_node* new_d_Dummy (dbg_info * dbgi, ir_mode * mode)
Construct a Dummy node.
Parameters
dbgi A pointer to debug information.
mode mode of the operations result
Definition at line 1108 of file gen_irnode.c.
References current_ir_graph, IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Dummy().
Referenced by new_Dummy().
ir_node* new_Dummy (ir_mode * mode)
Construct a Dummy node.
Parameters
mode mode of the operations result
Definition at line 1115 of file gen_irnode.c.
References new_d_Dummy().
ir_node* new_r_Dummy (ir_graph * irg, ir_mode * mode)
Construct a Dummy node.
Parameters
irg The IR graph the node belongs to.
mode mode of the operations result
Definition at line 1103 of file gen_irnode.c.
References new_rd_Dummy().
ir_node* new_rd_Dummy (dbg_info * dbgi, ir_graph * irg, ir_mode * mode)
Construct a Dummy node.
Parameters
dbgi A pointer to debug information.
irg The IR graph the node belongs to.
mode mode of the operations result
Definition at line 1090 of file gen_irnode.c.
References get_irg_start_block(), new_ir_node(), op_Dummy, optimize_node(), and verify_new_node().
Referenced by new_d_Dummy(), and new_r_Dummy().
Variable Documentation
ir_op* op_Dummy
Dummy opcode.
Definition at line 1697 of file nodes.h.
Referenced by get_op_Dummy(), and new_rd_Dummy().