[package]
name = "mjrt-src"
version = "0.1.0"
authors = ["Christian Schwarz <me@cschwarz.com>"]
edition = "2018"

[lib]
# we produce the rlib to satisfy cargo when this crate is used
# as a dependency by mjrt-bin
crate-type = ["staticlib", "rlib"]

[dependencies]
