libFirm: Align node
Align node
Nodes
A symbolic constant that represents the alignment of a type.
Functions
ir_node * new_rd_Align (dbg_info *dbgi, ir_graph *irg, ir_mode *mode, ir_type *type)
Construct an Align node.
ir_node * new_r_Align (ir_graph *irg, ir_mode *mode, ir_type *type)
Construct an Align node.
ir_node * new_d_Align (dbg_info *dbgi, ir_mode *mode, ir_type *type)
Construct an Align node.
ir_node * new_Align (ir_mode *mode, ir_type *type)
Construct an Align node.
int is_Align (const ir_node *node)
Test if node is a Align.
ir_type * get_Align_type (const ir_node *node)
Returns type attribute of an Align node.
void set_Align_type (ir_node *node, ir_type *type)
Sets type attribute of an Align node.
ir_op * get_op_Align (void)
Returns opcode for Align nodes.
Variables
ir_op * op_Align
Align opcode.
Detailed Description
A symbolic constant that represents the alignment of a type.
Function Documentation
ir_type* get_Align_type (const ir_node * node)
Returns type attribute of an Align node.
Definition at line 2960 of file gen_irnode.c.
ir_op* get_op_Align (void)
Returns opcode for Align nodes.
Definition at line 178 of file gen_irnode.c.
References op_Align.
int is_Align (const ir_node * node)
Test if node is a Align.
Returns
1 if the node is a Align node, 0 otherwise
Definition at line 2955 of file gen_irnode.c.
ir_node* new_Align (ir_mode * mode, ir_type * type)
Construct an Align node.
Parameters
mode mode of the operations result
type type to operate on
Definition at line 173 of file gen_irnode.c.
References new_d_Align().
ir_node* new_d_Align (dbg_info * dbgi, ir_mode * mode, ir_type * type)
Construct an Align node.
Parameters
dbgi A pointer to debug information.
mode mode of the operations result
type type to operate on
Definition at line 166 of file gen_irnode.c.
References current_ir_graph, IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Align().
Referenced by new_Align().
ir_node* new_r_Align (ir_graph * irg, ir_mode * mode, ir_type * type)
Construct an Align node.
Parameters
irg The IR graph the node belongs to.
mode mode of the operations result
type type to operate on
Definition at line 161 of file gen_irnode.c.
References new_rd_Align().
ir_node* new_rd_Align (dbg_info * dbgi, ir_graph * irg, ir_mode * mode, ir_type * type)
Construct an Align node.
Parameters
dbgi A pointer to debug information.
irg The IR graph the node belongs to.
mode mode of the operations result
type type to operate on
Definition at line 147 of file gen_irnode.c.
References get_irg_start_block(), new_ir_node(), op_Align, optimize_node(), and verify_new_node().
Referenced by new_d_Align(), and new_r_Align().
void set_Align_type (ir_node * node, ir_type * type)
Sets type attribute of an Align node.
Definition at line 2965 of file gen_irnode.c.
Variable Documentation
ir_op* op_Align
Align opcode.
Definition at line 357 of file nodes.h.
Referenced by get_op_Align(), and new_rd_Align().