libFirm: And node
And node
Nodes
returns the result of a bitwise and operation of its operands
Enumerations
enum n_And { n_And_left, n_And_right, n_And_max = n_And_right }
Input numbers for And node.
Functions
ir_node * new_rd_And (dbg_info *dbgi, ir_node *block, ir_node *irn_left, ir_node *irn_right)
Construct an And node.
ir_node * new_r_And (ir_node *block, ir_node *irn_left, ir_node *irn_right)
Construct an And node.
ir_node * new_d_And (dbg_info *dbgi, ir_node *irn_left, ir_node *irn_right)
Construct an And node.
ir_node * new_And (ir_node *irn_left, ir_node *irn_right)
Construct an And node.
int is_And (const ir_node *node)
Test if node is a And.
ir_node * get_And_left (const ir_node *node)
Returns left input of an And node.
void set_And_left (ir_node *node, ir_node *left)
Sets left input of an And node.
ir_node * get_And_right (const ir_node *node)
Returns right input of an And node.
void set_And_right (ir_node *node, ir_node *right)
Sets right input of an And node.
ir_op * get_op_And (void)
Returns opcode for And nodes.
Variables
ir_op * op_And
And opcode.
Detailed Description
returns the result of a bitwise and operation of its operands
Enumeration Type Documentation
enum n_And
Input numbers for And node.
Enumerator
n_And_left
first operand
n_And_right
second operand
n_And_max
Definition at line 540 of file nodes.h.
Function Documentation
ir_node* get_And_left (const ir_node * node)
Returns left input of an And node.
Definition at line 360 of file gen_irnode.c.
ir_node* get_And_right (const ir_node * node)
Returns right input of an And node.
Definition at line 370 of file gen_irnode.c.
ir_op* get_op_And (void)
Returns opcode for And nodes.
Definition at line 380 of file gen_irnode.c.
References op_And.
int is_And (const ir_node * node)
Test if node is a And.
Returns
1 if the node is a And node, 0 otherwise
Definition at line 2990 of file gen_irnode.c.
ir_node* new_And (ir_node * irn_left, ir_node * irn_right)
Construct an And node.
Parameters
irn_left left
irn_right right
Definition at line 355 of file gen_irnode.c.
References new_d_And().
ir_node* new_d_And (dbg_info * dbgi, ir_node * irn_left, ir_node * irn_right)
Construct an And node.
Parameters
dbgi A pointer to debug information.
irn_left left
irn_right right
Definition at line 348 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_And().
Referenced by new_And().
ir_node* new_r_And (ir_node * block, ir_node * irn_left, ir_node * irn_right)
Construct an And node.
Parameters
block The IR block the node belongs to.
irn_left left
irn_right right
Definition at line 343 of file gen_irnode.c.
References new_rd_And().
ir_node* new_rd_And (dbg_info * dbgi, ir_node * block, ir_node * irn_left, ir_node * irn_right)
Construct an And node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_left left
irn_right right
Definition at line 327 of file gen_irnode.c.
References get_irn_irg(), get_irn_mode(), new_ir_node(), op_And, optimize_node(), and verify_new_node().
Referenced by new_d_And(), and new_r_And().
void set_And_left (ir_node * node, ir_node * left)
Sets left input of an And node.
Definition at line 365 of file gen_irnode.c.
void set_And_right (ir_node * node, ir_node * right)
Sets right input of an And node.
Definition at line 375 of file gen_irnode.c.
Variable Documentation
ir_op* op_And
And opcode.
Definition at line 597 of file nodes.h.
Referenced by get_op_And(), and new_rd_And().