libFirm: Procedure Graph
Procedure Graph
This struct contains all information about a procedure.
Modules
Construction Support
Nodes
ir_node - a datatype representing a Firm node
Traversing
Traverse graphs:
Typedefs
typedef struct ir_graph ir_graph
Procedure Graph.
Enumerations
enum irg_callee_info_state { irg_callee_info_none, irg_callee_info_consistent, irg_callee_info_inconsistent }
state: callee_information_state Call nodes contain a list of possible callees.
enum ir_resources_t {
IR_RESOURCE_NONE = 0, IR_RESOURCE_BLOCK_VISITED = 1 << 0, IR_RESOURCE_BLOCK_MARK = 1 << 1, IR_RESOURCE_IRN_VISITED = 1 << 2,
IR_RESOURCE_IRN_LINK = 1 << 3, IR_RESOURCE_LOOP_LINK = 1 << 4, IR_RESOURCE_PHI_LIST = 1 << 5
}
Debug helpers: You can indicate whether you are currently using visited or block_visited flags.
enum ir_graph_constraints_t {
IR_GRAPH_CONSTRAINT_ARCH_DEP = 1U << 0, IR_GRAPH_CONSTRAINT_MODEB_LOWERED = 1U << 1, IR_GRAPH_CONSTRAINT_NORMALISATION2 = 1U << 2, IR_GRAPH_CONSTRAINT_OPTIMIZE_UNREACHABLE_CODE = 1U << 3,
IR_GRAPH_CONSTRAINT_CONSTRUCTION = 1U << 4, IR_GRAPH_CONSTRAINT_TARGET_LOWERED = 1U << 5, IR_GRAPH_CONSTRAINT_BACKEND = 1U << 6
}
graph constraints: These are typically used when lowering a graph for a target machine, typically you get stricter constraints the closer you get to a real machine.
enum ir_graph_properties_t {
IR_GRAPH_PROPERTIES_NONE = 0, IR_GRAPH_PROPERTY_NO_CRITICAL_EDGES = 1U << 0, IR_GRAPH_PROPERTY_NO_BADS = 1U << 1, IR_GRAPH_PROPERTY_NO_TUPLES = 1U << 2,
IR_GRAPH_PROPERTY_NO_UNREACHABLE_CODE = 1U << 3, IR_GRAPH_PROPERTY_ONE_RETURN = 1U << 4, IR_GRAPH_PROPERTY_CONSISTENT_DOMINANCE = 1U << 5, IR_GRAPH_PROPERTY_CONSISTENT_POSTDOMINANCE = 1U << 6,
IR_GRAPH_PROPERTY_CONSISTENT_DOMINANCE_FRONTIERS = 1U << 7, IR_GRAPH_PROPERTY_CONSISTENT_OUT_EDGES = 1U << 8, IR_GRAPH_PROPERTY_CONSISTENT_OUTS = 1U << 9, IR_GRAPH_PROPERTY_CONSISTENT_LOOPINFO = 1U << 10,
IR_GRAPH_PROPERTY_CONSISTENT_ENTITY_USAGE = 1U << 11, IR_GRAPH_PROPERTY_MANY_RETURNS = 1U << 12, IR_GRAPH_PROPERTIES_CONTROL_FLOW, IR_GRAPH_PROPERTIES_ALL
}
graph state.
Functions
ir_graph * new_ir_graph (ir_entity *ent, int n_loc)
Create a new ir graph to build ir for a procedure.
void free_ir_graph (ir_graph *irg)
Frees the passed irgraph.
ir_entity * get_irg_entity (const ir_graph *irg)
Returns the entity of an IR graph.
void set_irg_entity (ir_graph *irg, ir_entity *ent)
Sets the entity of an IR graph.
ir_type * get_irg_frame_type (ir_graph *irg)
Returns the frame type of an IR graph.
void set_irg_frame_type (ir_graph *irg, ir_type *ftp)
Sets the frame type of an IR graph.
ir_node * get_irg_start_block (const ir_graph *irg)
Returns the start block of an IR graph.
void set_irg_start_block (ir_graph *irg, ir_node *node)
Sets the start block of an IR graph.
ir_node * get_irg_start (const ir_graph *irg)
Returns the Start node of an IR graph.
void set_irg_start (ir_graph *irg, ir_node *node)
Sets the Start node of an IR graph.
ir_node * get_irg_end_block (const ir_graph *irg)
Returns the end block of an IR graph.
void set_irg_end_block (ir_graph *irg, ir_node *node)
Sets the end block of an IR graph.
ir_node * get_irg_end (const ir_graph *irg)
Returns the End node of an IR graph.
void set_irg_end (ir_graph *irg, ir_node *node)
Sets the End node of an IR graph.
ir_node * get_irg_frame (const ir_graph *irg)
Returns the node that represents the frame pointer of the given IR graph.
void set_irg_frame (ir_graph *irg, ir_node *node)
Sets the node that represents the frame pointer of the given IR graph.
ir_node * get_irg_initial_mem (const ir_graph *irg)
Returns the node that represents the initial memory of the given IR graph.
void set_irg_initial_mem (ir_graph *irg, ir_node *node)
Sets the node that represents the initial memory of the given IR graph.
ir_node * get_irg_args (const ir_graph *irg)
Returns the node that represents the argument pointer of the given IR graph.
void set_irg_args (ir_graph *irg, ir_node *node)
Sets the node that represents the argument pointer of the given IR graph.
ir_node * get_irg_no_mem (const ir_graph *irg)
Returns the NoMem node of the given IR graph.
void set_irg_no_mem (ir_graph *irg, ir_node *node)
Sets the NoMem node of graph irg.
int get_irg_n_locs (ir_graph *irg)
Returns the number of value numbers of an IR graph.
long get_irg_graph_nr (const ir_graph *irg)
Returns the graph number.
size_t get_irg_idx (const ir_graph *irg)
Returns the graph number.
ir_node * get_idx_irn (const ir_graph *irg, unsigned idx)
Returns the node for an index.
op_pin_state get_irg_pinned (const ir_graph *irg)
state: op_pin_state_pinned The graph is "op_pin_state_pinned" if all nodes are associated with a basic block.
irg_callee_info_state get_irg_callee_info_state (const ir_graph *irg)
Returns the callee_info_state of an IR graph.
void set_irg_callee_info_state (ir_graph *irg, irg_callee_info_state s)
Sets the callee_info_state of an IR graph.
void set_irg_link (ir_graph *irg, void *thing)
A void * field to link arbitrary information to the node.
void * get_irg_link (const ir_graph *irg)
Return void* field previously set by set_irg_link()
void inc_irg_visited (ir_graph *irg)
Increments node visited counter by one.
ir_visited_t get_irg_visited (const ir_graph *irg)
Returns node visited counter.
void set_irg_visited (ir_graph *irg, ir_visited_t i)
Sets node visited counter.
ir_visited_t get_max_irg_visited (void)
Returns interprocedural node visited counter.
void set_max_irg_visited (int val)
Sets interprocedural node visited counter.
ir_visited_t inc_max_irg_visited (void)
Increment interprocedural node visited counter by one.
void inc_irg_block_visited (ir_graph *irg)
Increments block visited counter by one.
ir_visited_t get_irg_block_visited (const ir_graph *irg)
Returns block visited counter.
void set_irg_block_visited (ir_graph *irg, ir_visited_t i)
Sets block visited counter.
void ir_reserve_resources (ir_graph *irg, ir_resources_t resources)
Reserves resources of a graph.
void ir_free_resources (ir_graph *irg, ir_resources_t resources)
Frees previously reserved resources.
ir_resources_t ir_resources_reserved (const ir_graph *irg)
Returns currently reserved resources.
void add_irg_constraints (ir_graph *irg, ir_graph_constraints_t constraints)
sets constraints on the graph irg
void clear_irg_constraints (ir_graph *irg, ir_graph_constraints_t constraints)
clears some graph constraints
int irg_is_constrained (const ir_graph *irg, ir_graph_constraints_t constraints)
queries whether irg is at least as constrained as constraints.
void add_irg_properties (ir_graph *irg, ir_graph_properties_t props)
sets some state properties on the graph
void clear_irg_properties (ir_graph *irg, ir_graph_properties_t props)
clears some graph properties
int irg_has_properties (const ir_graph *irg, ir_graph_properties_t props)
queries whether irg has the props properties set
void set_irg_loc_description (ir_graph *irg, int n, void *description)
Sets a description for local value n.
void * get_irg_loc_description (ir_graph *irg, int n)
Returns the description for local value n.
unsigned get_irg_last_idx (const ir_graph *irg)
Returns the last irn index for this graph.
void assure_irg_properties (ir_graph *irg, ir_graph_properties_t props)
Ensures that a graph fulfills all properties stated in state.
void confirm_irg_properties (ir_graph *irg, ir_graph_properties_t props)
Invalidates all graph properties/analysis data except the ones specified in props.
Detailed Description
This struct contains all information about a procedure.
It's allocated directly to memory.
The fields of ir_graph:
ent The entity describing this procedure.
anchor A node having several important nodes of the graph as its operands. The operands of the anchor are described in the following.
The beginning and end of a graph:
start_block This ir_node is the block that contains the unique start node of the procedure. With it it contains the Proj's on starts results. Further all Const nodes are placed in the start block.
start This ir_node is the unique start node of the procedure.
end_block This ir_node is the block that contains the unique end node of the procedure. This block contains no further nodes.
end This ir_node is the unique end node of the procedure.
The following nodes are Projs from the Start node, held by the anchor for simple access:
frame The ir_node producing the pointer to the stack frame of the procedure as output. This is the Proj node on the third output of the start node. This output of the start node is tagged as pns_frame_base. In FIRM most local variables are modeled as data flow edges. Static allocated arrays can not be represented as data flow edges. Therefore FIRM has to represent them in the stack frame.
initial_mem The memory monad passed to the function when calling it. This is Proj pn_Start_M of the Start node.
args The ir_node that produces the arguments of the method as its result. This is Proj pn_Start_T_args of the Start node.
no_mem The NoMem node is an auxiliary node. It is needed only once, so there is this globally reachable node.
Data structures that are private to a graph:
obst An obstack that contains all nodes.
current_block A pointer to the current block. Any node created with one of the node constructors (new_<opcode>) are assigned to this block. It can be set with set_cur_block(block). Only needed for ir construction.
n_loc An int giving the number of local variables in this procedure. This is needed for ir construction.
value_table This hash table (pset) is used for global value numbering for optimizing use in iropt.c.
visited A int used as flag to traverse the ir_graph.
block_visited A int used as a flag to traverse block nodes in the graph.
Typedef Documentation
typedef struct ir_graph ir_graph
Procedure Graph.
Definition at line 74 of file firm_types.h.
Enumeration Type Documentation
enum ir_graph_constraints_t
graph constraints: These are typically used when lowering a graph for a target machine, typically you get stricter constraints the closer you get to a real machine.
Enumerator
IR_GRAPH_CONSTRAINT_ARCH_DEP
Should not construct more nodes which irarch potentially breaks down.
IR_GRAPH_CONSTRAINT_MODEB_LOWERED
mode_b nodes have been lowered so you should not create any new nodes with mode_b (except for Cmp)
IR_GRAPH_CONSTRAINT_NORMALISATION2
There are normalisations where there is no "best" representative.
In this case we first normalise into 1 direction (!NORMALISATION2) and later in the other (NORMALISATION2).
IR_GRAPH_CONSTRAINT_OPTIMIZE_UNREACHABLE_CODE
Allows localopts to remove edges to unreachable code.
Warning: It is only safe to enable this when you are sure that you apply all localopts to the fixpoint. (=in optimize_graph_df)
IR_GRAPH_CONSTRAINT_CONSTRUCTION
The graph is being constructed: We have a current_block set, and blocks contain mapping of variable numbers to current values.
IR_GRAPH_CONSTRAINT_TARGET_LOWERED
Intermediate language constructs not supported by the backend have been lowered.
IR_GRAPH_CONSTRAINT_BACKEND
We have a backend graph: all data values have register constraints annotated.
Definition at line 309 of file irgraph.h.
enum ir_graph_properties_t
graph state.
The properties about a graph. Graph transformations may destroy these properties and have to explicitely state when they did not affect some properties and want to keep them.
Enumerator
IR_GRAPH_PROPERTIES_NONE
IR_GRAPH_PROPERTY_NO_CRITICAL_EDGES
graph contains no critical edges
IR_GRAPH_PROPERTY_NO_BADS
graph contains no Bad nodes
IR_GRAPH_PROPERTY_NO_TUPLES
No tuple nodes exist in the graph.
IR_GRAPH_PROPERTY_NO_UNREACHABLE_CODE
there exists no (obviously) unreachable code in the graph.
Unreachable in this context is code that you can't reach by following execution flow from the start block.
IR_GRAPH_PROPERTY_ONE_RETURN
graph contains at most one return
IR_GRAPH_PROPERTY_CONSISTENT_DOMINANCE
dominance information about the graph is valid
IR_GRAPH_PROPERTY_CONSISTENT_POSTDOMINANCE
postdominance information about the graph is valid
IR_GRAPH_PROPERTY_CONSISTENT_DOMINANCE_FRONTIERS
dominance frontiers information is calculated
IR_GRAPH_PROPERTY_CONSISTENT_OUT_EDGES
out edges (=iredges) are enable and there are no unused nodes that can be reached by following them
IR_GRAPH_PROPERTY_CONSISTENT_OUTS
outs (irouts) are computed and up to date
IR_GRAPH_PROPERTY_CONSISTENT_LOOPINFO
loopinfo is computed and up to date
IR_GRAPH_PROPERTY_CONSISTENT_ENTITY_USAGE
entity usage information is computed and up to date
IR_GRAPH_PROPERTY_MANY_RETURNS
graph contains as many returns as possible
IR_GRAPH_PROPERTIES_CONTROL_FLOW
List of all graph properties that are only affected by control flow changes.
IR_GRAPH_PROPERTIES_ALL
List of all graph properties.
Definition at line 365 of file irgraph.h.
enum ir_resources_t
Debug helpers: You can indicate whether you are currently using visited or block_visited flags.
If NDEBUG is not defined, then the compiler will abort if 2 parties try to use the flags.
Enumerator
IR_RESOURCE_NONE
no resource
IR_RESOURCE_BLOCK_VISITED
Block visited flags are used.
IR_RESOURCE_BLOCK_MARK
Block mark bits are used.
IR_RESOURCE_IRN_VISITED
IR-node visited flags are used.
IR_RESOURCE_IRN_LINK
IR-node link fields are used.
IR_RESOURCE_LOOP_LINK
IR-loop link fields are used.
IR_RESOURCE_PHI_LIST
Block Phi lists are used.
Definition at line 279 of file irgraph.h.
enum irg_callee_info_state
state: callee_information_state Call nodes contain a list of possible callees.
This list must be computed by an analysis.
It's strange that this state is administered on irg basis, as the information must be computed for the whole program, or not?
Enumerator
irg_callee_info_none
irg_callee_info_consistent
irg_callee_info_inconsistent
Definition at line 227 of file irgraph.h.
Function Documentation
void add_irg_constraints (ir_graph * irg, ir_graph_constraints_t constraints)
sets constraints on the graph irg
void add_irg_properties (ir_graph * irg, ir_graph_properties_t props)
sets some state properties on the graph
void assure_irg_properties (ir_graph * irg, ir_graph_properties_t props)
Ensures that a graph fulfills all properties stated in state.
Performs graph transformations if necessary.
void clear_irg_constraints (ir_graph * irg, ir_graph_constraints_t constraints)
clears some graph constraints
void clear_irg_properties (ir_graph * irg, ir_graph_properties_t props)
clears some graph properties
void confirm_irg_properties (ir_graph * irg, ir_graph_properties_t props)
Invalidates all graph properties/analysis data except the ones specified in props.
This should be called after a transformation phase.
void free_ir_graph (ir_graph * irg)
Frees the passed irgraph.
Deallocates all nodes in this graph and the ir_graph structure. Sets the field irgraph in the corresponding entity to NULL. Removes the irgraph from the list in irprog. Does not free types, entities or modes that are used only by this graph, nor the entity standing for this graph.
ir_node* get_idx_irn (const ir_graph * irg, unsigned idx)
Returns the node for an index.
Parameters
irg The graph.
idx The index you want the node for.
Returns
The node with that index or NULL, if there is no node with that index.
Note
The node you got might be dead.
See Also
get_irn_idx()
ir_node* get_irg_args (const ir_graph * irg)
Returns the node that represents the argument pointer of the given IR graph.
ir_visited_t get_irg_block_visited (const ir_graph * irg)
Returns block visited counter.
See Also
Visited Counters
irg_callee_info_state get_irg_callee_info_state (const ir_graph * irg)
Returns the callee_info_state of an IR graph.
ir_node* get_irg_end (const ir_graph * irg)
Returns the End node of an IR graph.
ir_node* get_irg_end_block (const ir_graph * irg)
Returns the end block of an IR graph.
Referenced by new_rd_End().
ir_entity* get_irg_entity (const ir_graph * irg)
Returns the entity of an IR graph.
ir_node* get_irg_frame (const ir_graph * irg)
Returns the node that represents the frame pointer of the given IR graph.
ir_type* get_irg_frame_type (ir_graph * irg)
Returns the frame type of an IR graph.
long get_irg_graph_nr (const ir_graph * irg)
Returns the graph number.
size_t get_irg_idx (const ir_graph * irg)
Returns the graph number.
This is a unique number for the graph and is smaller than get_irp_last_idx() Note: you cannot use this number for get_irp_irg()
ir_node* get_irg_initial_mem (const ir_graph * irg)
Returns the node that represents the initial memory of the given IR graph.
unsigned get_irg_last_idx (const ir_graph * irg)
Returns the last irn index for this graph.
void* get_irg_link (const ir_graph * irg)
Return void* field previously set by set_irg_link()
void* get_irg_loc_description (ir_graph * irg, int n)
Returns the description for local value n.
int get_irg_n_locs (ir_graph * irg)
Returns the number of value numbers of an IR graph.
ir_node* get_irg_no_mem (const ir_graph * irg)
Returns the NoMem node of the given IR graph.
op_pin_state get_irg_pinned (const ir_graph * irg)
state: op_pin_state_pinned The graph is "op_pin_state_pinned" if all nodes are associated with a basic block.
It is in state "op_pin_state_floats" if nodes are in arbitrary blocks. In state "op_pin_state_floats" the block predecessor is set in all nodes, but this can be an invalid block, i.e., the block is not a dominator of all the uses of the node. The enum op_pin_state is defined in irop.h.
ir_node* get_irg_start (const ir_graph * irg)
Returns the Start node of an IR graph.
ir_node* get_irg_start_block (const ir_graph * irg)
Returns the start block of an IR graph.
Referenced by new_rd_Address(), new_rd_Align(), new_rd_Bad(), new_rd_Const(), new_rd_Dummy(), new_rd_NoMem(), new_rd_Offset(), new_rd_Size(), new_rd_Start(), and new_rd_Unknown().
ir_visited_t get_irg_visited (const ir_graph * irg)
Returns node visited counter.
See Also
Visited Counters
ir_visited_t get_max_irg_visited (void)
Returns interprocedural node visited counter.
See Also
Visited Counters
void inc_irg_block_visited (ir_graph * irg)
Increments block visited counter by one.
See Also
Visited Counters, Block_block_visited(), mark_Block_block_visited()
void inc_irg_visited (ir_graph * irg)
Increments node visited counter by one.
See Also
Visited Counters, irn_visited(), mark_irn_visited()
ir_visited_t inc_max_irg_visited (void)
Increment interprocedural node visited counter by one.
See Also
Visited Counters
void ir_free_resources (ir_graph * irg, ir_resources_t resources)
Frees previously reserved resources.
void ir_reserve_resources (ir_graph * irg, ir_resources_t resources)
Reserves resources of a graph.
This is a debug tool: All code should properly allocate the resources it uses so if two interlocked algorithms use the same resources that bug will get detected.
ir_resources_t ir_resources_reserved (const ir_graph * irg)
Returns currently reserved resources.
int irg_has_properties (const ir_graph * irg, ir_graph_properties_t props)
queries whether irg has the props properties set
int irg_is_constrained (const ir_graph * irg, ir_graph_constraints_t constraints)
queries whether irg is at least as constrained as constraints.
Referenced by new_d_Add(), new_d_Address(), new_d_Align(), new_d_Alloc(), new_d_And(), new_d_Bad(), new_d_Bitcast(), new_d_Block(), new_d_Builtin(), new_d_Call(), new_d_Cmp(), new_d_Cond(), new_d_Confirm(), new_d_Const(), new_d_Conv(), new_d_CopyB(), new_d_Div(), new_d_Dummy(), new_d_End(), new_d_Eor(), new_d_Free(), new_d_IJmp(), new_d_Jmp(), new_d_Load(), new_d_Member(), new_d_Minus(), new_d_Mod(), new_d_Mul(), new_d_Mulh(), new_d_Mux(), new_d_NoMem(), new_d_Not(), new_d_Offset(), new_d_Or(), new_d_Phi(), new_d_Pin(), new_d_Proj(), new_d_Raise(), new_d_Return(), new_d_Sel(), new_d_Shl(), new_d_Shr(), new_d_Shrs(), new_d_Size(), new_d_Start(), new_d_Store(), new_d_Sub(), new_d_Switch(), new_d_Sync(), new_d_Tuple(), new_d_Unknown(), and new_rd_Block().
ir_graph* new_ir_graph (ir_entity * ent, int n_loc)
Create a new ir graph to build ir for a procedure.
Parameters
ent A pointer to an entity representing the procedure, i.e., the type of the entity must be of a method type.
n_loc The number of local variables in this procedure including the procedure parameters.
This constructor generates the basic infrastructure needed to represent a procedure in FIRM.
It allocates an ir_graph and sets the field irg of the entity ent to point to this graph. Further it allocates the following nodes needed for every procedure:
The start block containing a start node and Proj nodes for its results.
The end block containing an end node. This block is not matured after executing new_ir_graph() as predecessors need to be added to it. (Maturing a block means fixing its number of predecessors.)
The current block, which is empty and matured.
Further it enters the global store into the data structure of the start block that contains all valid values in this block (set_store()). This data structure is used to build the Phi nodes and removed after completion of the graph. There is no path from end to start in the graph after calling new_ir_graph().
The op_pin_state of the graph is set to "op_pin_state_pinned" if no global cse was performed on the graph. It is set to "op_pin_state_floats" if global cse was performed (and during construction: did actually change something). Code placement is necessary.
See Also
new_pseudo_ir_graph()
void set_irg_args (ir_graph * irg, ir_node * node)
Sets the node that represents the argument pointer of the given IR graph.
void set_irg_block_visited (ir_graph * irg, ir_visited_t i)
Sets block visited counter.
See Also
Visited Counters
void set_irg_callee_info_state (ir_graph * irg, irg_callee_info_state s)
Sets the callee_info_state of an IR graph.
void set_irg_end (ir_graph * irg, ir_node * node)
Sets the End node of an IR graph.
void set_irg_end_block (ir_graph * irg, ir_node * node)
Sets the end block of an IR graph.
void set_irg_entity (ir_graph * irg, ir_entity * ent)
Sets the entity of an IR graph.
void set_irg_frame (ir_graph * irg, ir_node * node)
Sets the node that represents the frame pointer of the given IR graph.
void set_irg_frame_type (ir_graph * irg, ir_type * ftp)
Sets the frame type of an IR graph.
void set_irg_initial_mem (ir_graph * irg, ir_node * node)
Sets the node that represents the initial memory of the given IR graph.
void set_irg_link (ir_graph * irg, void * thing)
A void * field to link arbitrary information to the node.
void set_irg_loc_description (ir_graph * irg, int n, void * description)
Sets a description for local value n.
void set_irg_no_mem (ir_graph * irg, ir_node * node)
Sets the NoMem node of graph irg.
void set_irg_start (ir_graph * irg, ir_node * node)
Sets the Start node of an IR graph.
void set_irg_start_block (ir_graph * irg, ir_node * node)
Sets the start block of an IR graph.
void set_irg_visited (ir_graph * irg, ir_visited_t i)
Sets node visited counter.
See Also
Visited Counters
void set_max_irg_visited (int val)
Sets interprocedural node visited counter.
See Also
Visited Counters