libFirm: Bitcast node
Bitcast node
Nodes
Converts a value between modes with different arithmetics but same number of bits by reinterpreting the bits in the new mode.
Enumerations
enum n_Bitcast { n_Bitcast_op, n_Bitcast_max = n_Bitcast_op }
Input numbers for Bitcast node.
Functions
ir_node * new_rd_Bitcast (dbg_info *dbgi, ir_node *block, ir_node *irn_op, ir_mode *mode)
Construct a Bitcast node.
ir_node * new_r_Bitcast (ir_node *block, ir_node *irn_op, ir_mode *mode)
Construct a Bitcast node.
ir_node * new_d_Bitcast (dbg_info *dbgi, ir_node *irn_op, ir_mode *mode)
Construct a Bitcast node.
ir_node * new_Bitcast (ir_node *irn_op, ir_mode *mode)
Construct a Bitcast node.
int is_Bitcast (const ir_node *node)
Test if node is a Bitcast.
ir_node * get_Bitcast_op (const ir_node *node)
Returns op input of a Bitcast node.
void set_Bitcast_op (ir_node *node, ir_node *op)
Sets op input of a Bitcast node.
ir_op * get_op_Bitcast (void)
Returns opcode for Bitcast nodes.
Variables
ir_op * op_Bitcast
Bitcast opcode.
Detailed Description
Converts a value between modes with different arithmetics but same number of bits by reinterpreting the bits in the new mode.
Enumeration Type Documentation
enum n_Bitcast
Input numbers for Bitcast node.
Enumerator
n_Bitcast_op
operand
n_Bitcast_max
Definition at line 687 of file nodes.h.
Function Documentation
ir_node* get_Bitcast_op (const ir_node * node)
Returns op input of a Bitcast node.
Definition at line 452 of file gen_irnode.c.
ir_op* get_op_Bitcast (void)
Returns opcode for Bitcast nodes.
Definition at line 462 of file gen_irnode.c.
References op_Bitcast.
int is_Bitcast (const ir_node * node)
Test if node is a Bitcast.
Returns
1 if the node is a Bitcast node, 0 otherwise
Definition at line 3000 of file gen_irnode.c.
ir_node* new_Bitcast (ir_node * irn_op, ir_mode * mode)
Construct a Bitcast node.
Parameters
irn_op op
mode mode of the operations result
Definition at line 447 of file gen_irnode.c.
References new_d_Bitcast().
ir_node* new_d_Bitcast (dbg_info * dbgi, ir_node * irn_op, ir_mode * mode)
Construct a Bitcast node.
Parameters
dbgi A pointer to debug information.
irn_op op
mode mode of the operations result
Definition at line 440 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Bitcast().
Referenced by new_Bitcast().
ir_node* new_r_Bitcast (ir_node * block, ir_node * irn_op, ir_mode * mode)
Construct a Bitcast node.
Parameters
block The IR block the node belongs to.
irn_op op
mode mode of the operations result
Definition at line 435 of file gen_irnode.c.
References new_rd_Bitcast().
ir_node* new_rd_Bitcast (dbg_info * dbgi, ir_node * block, ir_node * irn_op, ir_mode * mode)
Construct a Bitcast node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_op op
mode mode of the operations result
Definition at line 420 of file gen_irnode.c.
References get_irn_irg(), new_ir_node(), op_Bitcast, optimize_node(), and verify_new_node().
Referenced by new_d_Bitcast(), and new_r_Bitcast().
void set_Bitcast_op (ir_node * node, ir_node * op)
Sets op input of a Bitcast node.
Definition at line 457 of file gen_irnode.c.
Variable Documentation
ir_op* op_Bitcast
Bitcast opcode.
Definition at line 739 of file nodes.h.
Referenced by get_op_Bitcast(), and new_rd_Bitcast().