libFirm: Add node
Add node
Nodes
returns the sum of its operands
Enumerations
enum n_Add { n_Add_left, n_Add_right, n_Add_max = n_Add_right }
Input numbers for Add node.
Functions
ir_node * new_rd_Add (dbg_info *dbgi, ir_node *block, ir_node *irn_left, ir_node *irn_right)
Construct an Add node.
ir_node * new_r_Add (ir_node *block, ir_node *irn_left, ir_node *irn_right)
Construct an Add node.
ir_node * new_d_Add (dbg_info *dbgi, ir_node *irn_left, ir_node *irn_right)
Construct an Add node.
ir_node * new_Add (ir_node *irn_left, ir_node *irn_right)
Construct an Add node.
int is_Add (const ir_node *node)
Test if node is a Add.
ir_node * get_Add_left (const ir_node *node)
Returns left input of an Add node.
void set_Add_left (ir_node *node, ir_node *left)
Sets left input of an Add node.
ir_node * get_Add_right (const ir_node *node)
Returns right input of an Add node.
void set_Add_right (ir_node *node, ir_node *right)
Sets right input of an Add node.
ir_op * get_op_Add (void)
Returns opcode for Add nodes.
Variables
ir_op * op_Add
Add opcode.
Detailed Description
returns the sum of its operands
Enumeration Type Documentation
enum n_Add
Input numbers for Add node.
Enumerator
n_Add_left
first operand
n_Add_right
second operand
n_Add_max
Definition at line 179 of file nodes.h.
Function Documentation
ir_node* get_Add_left (const ir_node * node)
Returns left input of an Add node.
Definition at line 86 of file gen_irnode.c.
ir_node* get_Add_right (const ir_node * node)
Returns right input of an Add node.
Definition at line 96 of file gen_irnode.c.
ir_op* get_op_Add (void)
Returns opcode for Add nodes.
Definition at line 106 of file gen_irnode.c.
References op_Add.
int is_Add (const ir_node * node)
Test if node is a Add.
Returns
1 if the node is a Add node, 0 otherwise
Definition at line 2935 of file gen_irnode.c.
ir_node* new_Add (ir_node * irn_left, ir_node * irn_right)
Construct an Add node.
Parameters
irn_left left
irn_right right
Definition at line 81 of file gen_irnode.c.
References new_d_Add().
ir_node* new_d_Add (dbg_info * dbgi, ir_node * irn_left, ir_node * irn_right)
Construct an Add node.
Parameters
dbgi A pointer to debug information.
irn_left left
irn_right right
Definition at line 74 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Add().
Referenced by new_Add().
ir_node* new_r_Add (ir_node * block, ir_node * irn_left, ir_node * irn_right)
Construct an Add node.
Parameters
block The IR block the node belongs to.
irn_left left
irn_right right
Definition at line 69 of file gen_irnode.c.
References new_rd_Add().
ir_node* new_rd_Add (dbg_info * dbgi, ir_node * block, ir_node * irn_left, ir_node * irn_right)
Construct an Add node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_left left
irn_right right
Definition at line 53 of file gen_irnode.c.
References get_irn_irg(), get_irn_mode(), mode_is_reference(), new_ir_node(), op_Add, optimize_node(), and verify_new_node().
Referenced by new_d_Add(), and new_r_Add().
void set_Add_left (ir_node * node, ir_node * left)
Sets left input of an Add node.
Definition at line 91 of file gen_irnode.c.
void set_Add_right (ir_node * node, ir_node * right)
Sets right input of an Add node.
Definition at line 101 of file gen_irnode.c.
Variable Documentation
ir_op* op_Add
Add opcode.
Definition at line 236 of file nodes.h.
Referenced by get_op_Add(), and new_rd_Add().