libFirm: Mux node
Mux node
Nodes
returns the false or true operand depending on the value of the sel operand
Enumerations
enum n_Mux { n_Mux_sel, n_Mux_false, n_Mux_true, n_Mux_max = n_Mux_true }
Input numbers for Mux node.
Functions
ir_node * new_rd_Mux (dbg_info *dbgi, ir_node *block, ir_node *irn_sel, ir_node *irn_false, ir_node *irn_true)
Construct a Mux node.
ir_node * new_r_Mux (ir_node *block, ir_node *irn_sel, ir_node *irn_false, ir_node *irn_true)
Construct a Mux node.
ir_node * new_d_Mux (dbg_info *dbgi, ir_node *irn_sel, ir_node *irn_false, ir_node *irn_true)
Construct a Mux node.
ir_node * new_Mux (ir_node *irn_sel, ir_node *irn_false, ir_node *irn_true)
Construct a Mux node.
int is_Mux (const ir_node *node)
Test if node is a Mux.
ir_node * get_Mux_sel (const ir_node *node)
Returns sel input of a Mux node.
void set_Mux_sel (ir_node *node, ir_node *sel)
Sets sel input of a Mux node.
ir_node * get_Mux_false (const ir_node *node)
Returns false input of a Mux node.
void set_Mux_false (ir_node *node, ir_node *false_)
Sets false input of a Mux node.
ir_node * get_Mux_true (const ir_node *node)
Returns true input of a Mux node.
void set_Mux_true (ir_node *node, ir_node *true_)
Sets true input of a Mux node.
ir_op * get_op_Mux (void)
Returns opcode for Mux nodes.
Variables
ir_op * op_Mux
Mux opcode.
Detailed Description
returns the false or true operand depending on the value of the sel operand
Enumeration Type Documentation
enum n_Mux
Input numbers for Mux node.
Enumerator
n_Mux_sel
value making the output selection
n_Mux_false
selected if sel input is false
n_Mux_true
selected if sel input is true
n_Mux_max
Definition at line 2602 of file nodes.h.
Function Documentation
ir_node* get_Mux_false (const ir_node * node)
Returns false input of a Mux node.
Definition at line 1785 of file gen_irnode.c.
ir_node* get_Mux_sel (const ir_node * node)
Returns sel input of a Mux node.
Definition at line 1775 of file gen_irnode.c.
ir_node* get_Mux_true (const ir_node * node)
Returns true input of a Mux node.
Definition at line 1795 of file gen_irnode.c.
ir_op* get_op_Mux (void)
Returns opcode for Mux nodes.
Definition at line 1805 of file gen_irnode.c.
References op_Mux.
int is_Mux (const ir_node * node)
Test if node is a Mux.
Returns
1 if the node is a Mux node, 0 otherwise
Definition at line 3305 of file gen_irnode.c.
ir_node* new_d_Mux (dbg_info * dbgi, ir_node * irn_sel, ir_node * irn_false, ir_node * irn_true)
Construct a Mux node.
Parameters
dbgi A pointer to debug information.
irn_sel sel
irn_false false
irn_true true
Definition at line 1763 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Mux().
Referenced by new_Mux().
ir_node* new_Mux (ir_node * irn_sel, ir_node * irn_false, ir_node * irn_true)
Construct a Mux node.
Parameters
irn_sel sel
irn_false false
irn_true true
Definition at line 1770 of file gen_irnode.c.
References new_d_Mux().
ir_node* new_r_Mux (ir_node * block, ir_node * irn_sel, ir_node * irn_false, ir_node * irn_true)
Construct a Mux node.
Parameters
block The IR block the node belongs to.
irn_sel sel
irn_false false
irn_true true
Definition at line 1758 of file gen_irnode.c.
References new_rd_Mux().
ir_node* new_rd_Mux (dbg_info * dbgi, ir_node * block, ir_node * irn_sel, ir_node * irn_false, ir_node * irn_true)
Construct a Mux node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_sel sel
irn_false false
irn_true true
Definition at line 1741 of file gen_irnode.c.
References get_irn_irg(), get_irn_mode(), new_ir_node(), op_Mux, optimize_node(), and verify_new_node().
Referenced by new_d_Mux(), and new_r_Mux().
void set_Mux_false (ir_node * node, ir_node * false_)
Sets false input of a Mux node.
Definition at line 1790 of file gen_irnode.c.
void set_Mux_sel (ir_node * node, ir_node * sel)
Sets sel input of a Mux node.
Definition at line 1780 of file gen_irnode.c.
void set_Mux_true (ir_node * node, ir_node * true_)
Sets true input of a Mux node.
Definition at line 1800 of file gen_irnode.c.
Variable Documentation
ir_op* op_Mux
Mux opcode.
Definition at line 2668 of file nodes.h.
Referenced by get_op_Mux(), and new_rd_Mux().