libFirm: Free node
Free node
Nodes
Frees a block of memory previously allocated by an Alloc node.
Enumerations
enum n_Free { n_Free_mem, n_Free_ptr, n_Free_max = n_Free_ptr }
Input numbers for Free node.
Functions
ir_node * new_rd_Free (dbg_info *dbgi, ir_node *block, ir_node *irn_mem, ir_node *irn_ptr)
Construct a Free node.
ir_node * new_r_Free (ir_node *block, ir_node *irn_mem, ir_node *irn_ptr)
Construct a Free node.
ir_node * new_d_Free (dbg_info *dbgi, ir_node *irn_mem, ir_node *irn_ptr)
Construct a Free node.
ir_node * new_Free (ir_node *irn_mem, ir_node *irn_ptr)
Construct a Free node.
int is_Free (const ir_node *node)
Test if node is a Free.
ir_node * get_Free_mem (const ir_node *node)
Returns mem input of a Free node.
void set_Free_mem (ir_node *node, ir_node *mem)
Sets mem input of a Free node.
ir_node * get_Free_ptr (const ir_node *node)
Returns ptr input of a Free node.
void set_Free_ptr (ir_node *node, ir_node *ptr)
Sets ptr input of a Free node.
ir_op * get_op_Free (void)
Returns opcode for Free nodes.
Variables
ir_op * op_Free
Free opcode.
Detailed Description
Frees a block of memory previously allocated by an Alloc node.
Enumeration Type Documentation
enum n_Free
Input numbers for Free node.
Enumerator
n_Free_mem
memory dependency
n_Free_ptr
pointer to the object to free
n_Free_max
Definition at line 1856 of file nodes.h.
Function Documentation
ir_node* get_Free_mem (const ir_node * node)
Returns mem input of a Free node.
Definition at line 1271 of file gen_irnode.c.
ir_node* get_Free_ptr (const ir_node * node)
Returns ptr input of a Free node.
Definition at line 1281 of file gen_irnode.c.
ir_op* get_op_Free (void)
Returns opcode for Free nodes.
Definition at line 1291 of file gen_irnode.c.
References op_Free.
int is_Free (const ir_node * node)
Test if node is a Free.
Returns
1 if the node is a Free node, 0 otherwise
Definition at line 3195 of file gen_irnode.c.
ir_node* new_d_Free (dbg_info * dbgi, ir_node * irn_mem, ir_node * irn_ptr)
Construct a Free node.
Parameters
dbgi A pointer to debug information.
irn_mem mem
irn_ptr ptr
Definition at line 1259 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Free().
Referenced by new_Free().
ir_node* new_Free (ir_node * irn_mem, ir_node * irn_ptr)
Construct a Free node.
Parameters
irn_mem mem
irn_ptr ptr
Definition at line 1266 of file gen_irnode.c.
References new_d_Free().
ir_node* new_r_Free (ir_node * block, ir_node * irn_mem, ir_node * irn_ptr)
Construct a Free node.
Parameters
block The IR block the node belongs to.
irn_mem mem
irn_ptr ptr
Definition at line 1254 of file gen_irnode.c.
References new_rd_Free().
ir_node* new_rd_Free (dbg_info * dbgi, ir_node * block, ir_node * irn_mem, ir_node * irn_ptr)
Construct a Free node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_mem mem
irn_ptr ptr
Definition at line 1238 of file gen_irnode.c.
References get_irn_irg(), mode_M, new_ir_node(), op_Free, optimize_node(), and verify_new_node().
Referenced by new_d_Free(), and new_r_Free().
void set_Free_mem (ir_node * node, ir_node * mem)
Sets mem input of a Free node.
Definition at line 1276 of file gen_irnode.c.
void set_Free_ptr (ir_node * node, ir_node * ptr)
Sets ptr input of a Free node.
Definition at line 1286 of file gen_irnode.c.
Variable Documentation
ir_op* op_Free
Free opcode.
Definition at line 1913 of file nodes.h.
Referenced by get_op_Free(), and new_rd_Free().