libFirm: Offset node
Offset node
Nodes
Symbolic constant that represents the offset of an entity in its owner type.
Functions
ir_node * new_rd_Offset (dbg_info *dbgi, ir_graph *irg, ir_mode *mode, ir_entity *entity)
Construct an Offset node.
ir_node * new_r_Offset (ir_graph *irg, ir_mode *mode, ir_entity *entity)
Construct an Offset node.
ir_node * new_d_Offset (dbg_info *dbgi, ir_mode *mode, ir_entity *entity)
Construct an Offset node.
ir_node * new_Offset (ir_mode *mode, ir_entity *entity)
Construct an Offset node.
int is_Offset (const ir_node *node)
Test if node is a Offset.
ir_entity * get_Offset_entity (const ir_node *node)
Returns entity attribute of an Offset node.
void set_Offset_entity (ir_node *node, ir_entity *entity)
Sets entity attribute of an Offset node.
ir_op * get_op_Offset (void)
Returns opcode for Offset nodes.
Variables
ir_op * op_Offset
Offset opcode.
Detailed Description
Symbolic constant that represents the offset of an entity in its owner type.
Function Documentation
ir_entity* get_Offset_entity (const ir_node * node)
Returns entity attribute of an Offset node.
Definition at line 3325 of file gen_irnode.c.
ir_op* get_op_Offset (void)
Returns opcode for Offset nodes.
Definition at line 1923 of file gen_irnode.c.
References op_Offset.
int is_Offset (const ir_node * node)
Test if node is a Offset.
Returns
1 if the node is a Offset node, 0 otherwise
Definition at line 3320 of file gen_irnode.c.
ir_node* new_d_Offset (dbg_info * dbgi, ir_mode * mode, ir_entity * entity)
Construct an Offset node.
Parameters
dbgi A pointer to debug information.
mode mode of the operations result
entity entity to operate on
Definition at line 1911 of file gen_irnode.c.
References current_ir_graph, IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Offset().
Referenced by new_Offset().
ir_node* new_Offset (ir_mode * mode, ir_entity * entity)
Construct an Offset node.
Parameters
mode mode of the operations result
entity entity to operate on
Definition at line 1918 of file gen_irnode.c.
References new_d_Offset().
ir_node* new_r_Offset (ir_graph * irg, ir_mode * mode, ir_entity * entity)
Construct an Offset node.
Parameters
irg The IR graph the node belongs to.
mode mode of the operations result
entity entity to operate on
Definition at line 1906 of file gen_irnode.c.
References new_rd_Offset().
ir_node* new_rd_Offset (dbg_info * dbgi, ir_graph * irg, ir_mode * mode, ir_entity * entity)
Construct an Offset node.
Parameters
dbgi A pointer to debug information.
irg The IR graph the node belongs to.
mode mode of the operations result
entity entity to operate on
Definition at line 1892 of file gen_irnode.c.
References get_irg_start_block(), new_ir_node(), op_Offset, optimize_node(), and verify_new_node().
Referenced by new_d_Offset(), and new_r_Offset().
void set_Offset_entity (ir_node * node, ir_entity * entity)
Sets entity attribute of an Offset node.
Definition at line 3330 of file gen_irnode.c.
Variable Documentation
ir_op* op_Offset
Offset opcode.
Definition at line 2844 of file nodes.h.
Referenced by get_op_Offset(), and new_rd_Offset().