libFirm: Size node
Size node
Nodes
A symbolic constant that represents the size of a type.
Functions
ir_node * new_rd_Size (dbg_info *dbgi, ir_graph *irg, ir_mode *mode, ir_type *type)
Construct a Size node.
ir_node * new_r_Size (ir_graph *irg, ir_mode *mode, ir_type *type)
Construct a Size node.
ir_node * new_d_Size (dbg_info *dbgi, ir_mode *mode, ir_type *type)
Construct a Size node.
ir_node * new_Size (ir_mode *mode, ir_type *type)
Construct a Size node.
int is_Size (const ir_node *node)
Test if node is a Size.
ir_type * get_Size_type (const ir_node *node)
Returns type attribute of a Size node.
void set_Size_type (ir_node *node, ir_type *type)
Sets type attribute of a Size node.
ir_op * get_op_Size (void)
Returns opcode for Size nodes.
Variables
ir_op * op_Size
Size opcode.
Detailed Description
A symbolic constant that represents the size of a type.
Function Documentation
ir_op* get_op_Size (void)
Returns opcode for Size nodes.
Definition at line 2531 of file gen_irnode.c.
References op_Size.
ir_type* get_Size_type (const ir_node * node)
Returns type attribute of a Size node.
Definition at line 3420 of file gen_irnode.c.
int is_Size (const ir_node * node)
Test if node is a Size.
Returns
1 if the node is a Size node, 0 otherwise
Definition at line 3415 of file gen_irnode.c.
ir_node* new_d_Size (dbg_info * dbgi, ir_mode * mode, ir_type * type)
Construct a Size node.
Parameters
dbgi A pointer to debug information.
mode mode of the operations result
type type to operate on
Definition at line 2519 of file gen_irnode.c.
References current_ir_graph, IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Size().
Referenced by new_Size().
ir_node* new_r_Size (ir_graph * irg, ir_mode * mode, ir_type * type)
Construct a Size node.
Parameters
irg The IR graph the node belongs to.
mode mode of the operations result
type type to operate on
Definition at line 2514 of file gen_irnode.c.
References new_rd_Size().
ir_node* new_rd_Size (dbg_info * dbgi, ir_graph * irg, ir_mode * mode, ir_type * type)
Construct a Size node.
Parameters
dbgi A pointer to debug information.
irg The IR graph the node belongs to.
mode mode of the operations result
type type to operate on
Definition at line 2500 of file gen_irnode.c.
References get_irg_start_block(), new_ir_node(), op_Size, optimize_node(), and verify_new_node().
Referenced by new_d_Size(), and new_r_Size().
ir_node* new_Size (ir_mode * mode, ir_type * type)
Construct a Size node.
Parameters
mode mode of the operations result
type type to operate on
Definition at line 2526 of file gen_irnode.c.
References new_d_Size().
void set_Size_type (ir_node * node, ir_type * type)
Sets type attribute of a Size node.
Definition at line 3425 of file gen_irnode.c.
Variable Documentation
ir_op* op_Size
Size opcode.
Definition at line 3687 of file nodes.h.
Referenced by get_op_Size(), and new_rd_Size().