libFirm: Conv node
Conv node
Nodes
Converts values between modes.
Enumerations
enum n_Conv { n_Conv_op, n_Conv_max = n_Conv_op }
Input numbers for Conv node.
Functions
ir_node * new_rd_Conv (dbg_info *dbgi, ir_node *block, ir_node *irn_op, ir_mode *mode)
Construct a Conv node.
ir_node * new_r_Conv (ir_node *block, ir_node *irn_op, ir_mode *mode)
Construct a Conv node.
ir_node * new_d_Conv (dbg_info *dbgi, ir_node *irn_op, ir_mode *mode)
Construct a Conv node.
ir_node * new_Conv (ir_node *irn_op, ir_mode *mode)
Construct a Conv node.
int is_Conv (const ir_node *node)
Test if node is a Conv.
ir_node * get_Conv_op (const ir_node *node)
Returns op input of a Conv node.
void set_Conv_op (ir_node *node, ir_node *op)
Sets op input of a Conv node.
ir_op * get_op_Conv (void)
Returns opcode for Conv nodes.
Variables
ir_op * op_Conv
Conv opcode.
Detailed Description
Converts values between modes.
Enumeration Type Documentation
enum n_Conv
Input numbers for Conv node.
Enumerator
n_Conv_op
operand
n_Conv_max
Definition at line 1358 of file nodes.h.
Function Documentation
ir_node* get_Conv_op (const ir_node * node)
Returns op input of a Conv node.
Definition at line 926 of file gen_irnode.c.
ir_op* get_op_Conv (void)
Returns opcode for Conv nodes.
Definition at line 936 of file gen_irnode.c.
References op_Conv.
int is_Conv (const ir_node * node)
Test if node is a Conv.
Returns
1 if the node is a Conv node, 0 otherwise
Definition at line 3120 of file gen_irnode.c.
ir_node* new_Conv (ir_node * irn_op, ir_mode * mode)
Construct a Conv node.
Parameters
irn_op op
mode mode of the operations result
Definition at line 921 of file gen_irnode.c.
References new_d_Conv().
ir_node* new_d_Conv (dbg_info * dbgi, ir_node * irn_op, ir_mode * mode)
Construct a Conv node.
Parameters
dbgi A pointer to debug information.
irn_op op
mode mode of the operations result
Definition at line 914 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Conv().
Referenced by new_Conv().
ir_node* new_r_Conv (ir_node * block, ir_node * irn_op, ir_mode * mode)
Construct a Conv node.
Parameters
block The IR block the node belongs to.
irn_op op
mode mode of the operations result
Definition at line 909 of file gen_irnode.c.
References new_rd_Conv().
ir_node* new_rd_Conv (dbg_info * dbgi, ir_node * block, ir_node * irn_op, ir_mode * mode)
Construct a Conv node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_op op
mode mode of the operations result
Definition at line 894 of file gen_irnode.c.
References get_irn_irg(), new_ir_node(), op_Conv, optimize_node(), and verify_new_node().
Referenced by new_d_Conv(), and new_r_Conv().
void set_Conv_op (ir_node * node, ir_node * op)
Sets op input of a Conv node.
Definition at line 931 of file gen_irnode.c.
Variable Documentation
ir_op* op_Conv
Conv opcode.
Definition at line 1410 of file nodes.h.
Referenced by get_op_Conv(), and new_rd_Conv().