libFirm: Const node
Const node
Nodes
Returns a constant value.
Functions
ir_node * new_rd_Const_long (dbg_info *db, ir_graph *irg, ir_mode *mode, long value)
Constructor for a Const node.
ir_node * new_r_Const_long (ir_graph *irg, ir_mode *mode, long value)
Constructor for a Const node.
ir_node * new_d_Const_long (dbg_info *db, ir_mode *mode, long value)
ir_node * new_Const_long (ir_mode *mode, long value)
Make a const from a long.
int is_Const_null (const ir_node *node)
Returns non-zero if the given Const node represents the 0 constant.
int is_Const_one (const ir_node *node)
Returns non-zero if the given Const node represents the 1 constant.
int is_Const_all_one (const ir_node *node)
Returns non-zero if the given Const node represents the constant with all bits set.
ir_node * new_rd_Const (dbg_info *dbgi, ir_graph *irg, ir_tarval *tarval)
Construct a Const node.
ir_node * new_r_Const (ir_graph *irg, ir_tarval *tarval)
Construct a Const node.
ir_node * new_d_Const (dbg_info *dbgi, ir_tarval *tarval)
Construct a Const node.
ir_node * new_Const (ir_tarval *tarval)
Construct a Const node.
int is_Const (const ir_node *node)
Test if node is a Const.
ir_tarval * get_Const_tarval (const ir_node *node)
Returns tarval attribute of a Const node.
void set_Const_tarval (ir_node *node, ir_tarval *tarval)
Sets tarval attribute of a Const node.
ir_op * get_op_Const (void)
Returns opcode for Const nodes.
Variables
ir_op * op_Const
Const opcode.
Detailed Description
Returns a constant value.
Function Documentation
ir_tarval* get_Const_tarval (const ir_node * node)
Returns tarval attribute of a Const node.
Definition at line 3110 of file gen_irnode.c.
ir_op* get_op_Const (void)
Returns opcode for Const nodes.
Definition at line 889 of file gen_irnode.c.
References op_Const.
int is_Const (const ir_node * node)
Test if node is a Const.
Returns
1 if the node is a Const node, 0 otherwise
Definition at line 3105 of file gen_irnode.c.
int is_Const_all_one (const ir_node * node)
Returns non-zero if the given Const node represents the constant with all bits set.
int is_Const_null (const ir_node * node)
Returns non-zero if the given Const node represents the 0 constant.
int is_Const_one (const ir_node * node)
Returns non-zero if the given Const node represents the 1 constant.
ir_node* new_Const (ir_tarval * tarval)
Construct a Const node.
Parameters
tarval constant value (a tarval object)
Definition at line 884 of file gen_irnode.c.
References new_d_Const().
ir_node* new_Const_long (ir_mode * mode, long value)
Make a const from a long.
This is just convenience for the usual new_Const(mode, tarval_from_long(mode, ...)) pain.
Parameters
mode The mode for the const.
value The value of the constant.
Returns
A new const node.
ir_node* new_d_Const (dbg_info * dbgi, ir_tarval * tarval)
Construct a Const node.
Parameters
dbgi A pointer to debug information.
tarval constant value (a tarval object)
Definition at line 877 of file gen_irnode.c.
References current_ir_graph, IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Const().
Referenced by new_Const().
ir_node* new_d_Const_long (dbg_info * db, ir_mode * mode, long value)
See Also
new_rd_Const_long()
Parameters
db A pointer for debug information.
mode The mode of the operands and results.
value A value from which the tarval is made.
ir_node* new_r_Const (ir_graph * irg, ir_tarval * tarval)
Construct a Const node.
Parameters
irg The IR graph the node belongs to.
tarval constant value (a tarval object)
Definition at line 872 of file gen_irnode.c.
References new_rd_Const().
ir_node* new_r_Const_long (ir_graph * irg, ir_mode * mode, long value)
Constructor for a Const node.
Adds the node to the start block.
The constant represents a target value.
Parameters
irg The IR graph the node belongs to.
mode The mode of the operands and the results.
value A value from which the tarval is made.
ir_node* new_rd_Const (dbg_info * dbgi, ir_graph * irg, ir_tarval * tarval)
Construct a Const node.
Parameters
dbgi A pointer to debug information.
irg The IR graph the node belongs to.
tarval constant value (a tarval object)
Definition at line 858 of file gen_irnode.c.
References get_irg_start_block(), get_tarval_mode(), new_ir_node(), op_Const, optimize_node(), and verify_new_node().
Referenced by new_d_Const(), and new_r_Const().
ir_node* new_rd_Const_long (dbg_info * db, ir_graph * irg, ir_mode * mode, long value)
Constructor for a Const node.
Adds the node to the start block.
The constant represents a target value.
Parameters
db A pointer for debug information.
irg The IR graph the node belongs to.
mode The mode of the operands and results.
value A value from which the tarval is made.
void set_Const_tarval (ir_node * node, ir_tarval * tarval)
Sets tarval attribute of a Const node.
Definition at line 3115 of file gen_irnode.c.
Variable Documentation
ir_op* op_Const
Const opcode.
Definition at line 1341 of file nodes.h.
Referenced by get_op_Const(), and new_rd_Const().