libFirm: Or node
Or node
Nodes
returns the result of a bitwise or operation of its operands
Enumerations
enum n_Or { n_Or_left, n_Or_right, n_Or_max = n_Or_right }
Input numbers for Or node.
Functions
ir_node * new_rd_Or (dbg_info *dbgi, ir_node *block, ir_node *irn_left, ir_node *irn_right)
Construct an Or node.
ir_node * new_r_Or (ir_node *block, ir_node *irn_left, ir_node *irn_right)
Construct an Or node.
ir_node * new_d_Or (dbg_info *dbgi, ir_node *irn_left, ir_node *irn_right)
Construct an Or node.
ir_node * new_Or (ir_node *irn_left, ir_node *irn_right)
Construct an Or node.
int is_Or (const ir_node *node)
Test if node is a Or.
ir_node * get_Or_left (const ir_node *node)
Returns left input of an Or node.
void set_Or_left (ir_node *node, ir_node *left)
Sets left input of an Or node.
ir_node * get_Or_right (const ir_node *node)
Returns right input of an Or node.
void set_Or_right (ir_node *node, ir_node *right)
Sets right input of an Or node.
ir_op * get_op_Or (void)
Returns opcode for Or nodes.
Variables
ir_op * op_Or
Or opcode.
Detailed Description
returns the result of a bitwise or operation of its operands
Enumeration Type Documentation
enum n_Or
Input numbers for Or node.
Enumerator
n_Or_left
first operand
n_Or_right
second operand
n_Or_max
Definition at line 2861 of file nodes.h.
Function Documentation
ir_op* get_op_Or (void)
Returns opcode for Or nodes.
Definition at line 1981 of file gen_irnode.c.
References op_Or.
ir_node* get_Or_left (const ir_node * node)
Returns left input of an Or node.
Definition at line 1961 of file gen_irnode.c.
ir_node* get_Or_right (const ir_node * node)
Returns right input of an Or node.
Definition at line 1971 of file gen_irnode.c.
int is_Or (const ir_node * node)
Test if node is a Or.
Returns
1 if the node is a Or node, 0 otherwise
Definition at line 3335 of file gen_irnode.c.
ir_node* new_d_Or (dbg_info * dbgi, ir_node * irn_left, ir_node * irn_right)
Construct an Or node.
Parameters
dbgi A pointer to debug information.
irn_left left
irn_right right
Definition at line 1949 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Or().
Referenced by new_Or().
ir_node* new_Or (ir_node * irn_left, ir_node * irn_right)
Construct an Or node.
Parameters
irn_left left
irn_right right
Definition at line 1956 of file gen_irnode.c.
References new_d_Or().
ir_node* new_r_Or (ir_node * block, ir_node * irn_left, ir_node * irn_right)
Construct an Or node.
Parameters
block The IR block the node belongs to.
irn_left left
irn_right right
Definition at line 1944 of file gen_irnode.c.
References new_rd_Or().
ir_node* new_rd_Or (dbg_info * dbgi, ir_node * block, ir_node * irn_left, ir_node * irn_right)
Construct an Or node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_left left
irn_right right
Definition at line 1928 of file gen_irnode.c.
References get_irn_irg(), get_irn_mode(), new_ir_node(), op_Or, optimize_node(), and verify_new_node().
Referenced by new_d_Or(), and new_r_Or().
void set_Or_left (ir_node * node, ir_node * left)
Sets left input of an Or node.
Definition at line 1966 of file gen_irnode.c.
void set_Or_right (ir_node * node, ir_node * right)
Sets right input of an Or node.
Definition at line 1976 of file gen_irnode.c.
Variable Documentation
ir_op* op_Or
Or opcode.
Definition at line 2918 of file nodes.h.
Referenced by get_op_Or(), and new_rd_Or().