libFirm: Not node
Not node
Nodes
returns the bitwise complement of a value.
Enumerations
enum n_Not { n_Not_op, n_Not_max = n_Not_op }
Input numbers for Not node.
Functions
ir_node * new_rd_Not (dbg_info *dbgi, ir_node *block, ir_node *irn_op)
Construct a Not node.
ir_node * new_r_Not (ir_node *block, ir_node *irn_op)
Construct a Not node.
ir_node * new_d_Not (dbg_info *dbgi, ir_node *irn_op)
Construct a Not node.
ir_node * new_Not (ir_node *irn_op)
Construct a Not node.
int is_Not (const ir_node *node)
Test if node is a Not.
ir_node * get_Not_op (const ir_node *node)
Returns op input of a Not node.
void set_Not_op (ir_node *node, ir_node *op)
Sets op input of a Not node.
ir_op * get_op_Not (void)
Returns opcode for Not nodes.
Variables
ir_op * op_Not
Not opcode.
Detailed Description
returns the bitwise complement of a value.
Works for boolean values, too.
Enumeration Type Documentation
enum n_Not
Input numbers for Not node.
Enumerator
n_Not_op
operand
n_Not_max
Definition at line 2734 of file nodes.h.
Function Documentation
ir_node* get_Not_op (const ir_node * node)
Returns op input of a Not node.
Definition at line 1877 of file gen_irnode.c.
ir_op* get_op_Not (void)
Returns opcode for Not nodes.
Definition at line 1887 of file gen_irnode.c.
References op_Not.
int is_Not (const ir_node * node)
Test if node is a Not.
Returns
1 if the node is a Not node, 0 otherwise
Definition at line 3315 of file gen_irnode.c.
ir_node* new_d_Not (dbg_info * dbgi, ir_node * irn_op)
Construct a Not node.
Parameters
dbgi A pointer to debug information.
irn_op op
Definition at line 1865 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Not().
Referenced by new_Not().
ir_node* new_Not (ir_node * irn_op)
Construct a Not node.
Parameters
irn_op op
Definition at line 1872 of file gen_irnode.c.
References new_d_Not().
ir_node* new_r_Not (ir_node * block, ir_node * irn_op)
Construct a Not node.
Parameters
block The IR block the node belongs to.
irn_op op
Definition at line 1860 of file gen_irnode.c.
References new_rd_Not().
ir_node* new_rd_Not (dbg_info * dbgi, ir_node * block, ir_node * irn_op)
Construct a Not node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_op op
Definition at line 1845 of file gen_irnode.c.
References get_irn_irg(), get_irn_mode(), new_ir_node(), op_Not, optimize_node(), and verify_new_node().
Referenced by new_d_Not(), and new_r_Not().
void set_Not_op (ir_node * node, ir_node * op)
Sets op input of a Not node.
Definition at line 1882 of file gen_irnode.c.
Variable Documentation
ir_op* op_Not
Not opcode.
Definition at line 2782 of file nodes.h.
Referenced by get_op_Not(), and new_rd_Not().