libFirm: Shl node
Shl node
Nodes
Returns its first operands bits shifted left by the amount of the 2nd operand.
Enumerations
enum n_Shl { n_Shl_left, n_Shl_right, n_Shl_max = n_Shl_right }
Input numbers for Shl node.
Functions
ir_node * new_rd_Shl (dbg_info *dbgi, ir_node *block, ir_node *irn_left, ir_node *irn_right)
Construct a Shl node.
ir_node * new_r_Shl (ir_node *block, ir_node *irn_left, ir_node *irn_right)
Construct a Shl node.
ir_node * new_d_Shl (dbg_info *dbgi, ir_node *irn_left, ir_node *irn_right)
Construct a Shl node.
ir_node * new_Shl (ir_node *irn_left, ir_node *irn_right)
Construct a Shl node.
int is_Shl (const ir_node *node)
Test if node is a Shl.
ir_node * get_Shl_left (const ir_node *node)
Returns left input of a Shl node.
void set_Shl_left (ir_node *node, ir_node *left)
Sets left input of a Shl node.
ir_node * get_Shl_right (const ir_node *node)
Returns right input of a Shl node.
void set_Shl_right (ir_node *node, ir_node *right)
Sets right input of a Shl node.
ir_op * get_op_Shl (void)
Returns opcode for Shl nodes.
Variables
ir_op * op_Shl
Shl opcode.
Detailed Description
Returns its first operands bits shifted left by the amount of the 2nd operand.
The right input (shift amount) must be an unsigned integer value. If the result mode has modulo_shift!=0, then the effective shift amount is the right input modulo this modulo_shift amount.
Enumeration Type Documentation
enum n_Shl
Input numbers for Shl node.
Enumerator
n_Shl_left
first operand
n_Shl_right
second operand
n_Shl_max
Definition at line 3411 of file nodes.h.
Function Documentation
ir_op* get_op_Shl (void)
Returns opcode for Shl nodes.
Definition at line 2379 of file gen_irnode.c.
References op_Shl.
ir_node* get_Shl_left (const ir_node * node)
Returns left input of a Shl node.
Definition at line 2359 of file gen_irnode.c.
ir_node* get_Shl_right (const ir_node * node)
Returns right input of a Shl node.
Definition at line 2369 of file gen_irnode.c.
int is_Shl (const ir_node * node)
Test if node is a Shl.
Returns
1 if the node is a Shl node, 0 otherwise
Definition at line 3400 of file gen_irnode.c.
ir_node* new_d_Shl (dbg_info * dbgi, ir_node * irn_left, ir_node * irn_right)
Construct a Shl node.
Parameters
dbgi A pointer to debug information.
irn_left left
irn_right right
Definition at line 2347 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Shl().
Referenced by new_Shl().
ir_node* new_r_Shl (ir_node * block, ir_node * irn_left, ir_node * irn_right)
Construct a Shl node.
Parameters
block The IR block the node belongs to.
irn_left left
irn_right right
Definition at line 2342 of file gen_irnode.c.
References new_rd_Shl().
ir_node* new_rd_Shl (dbg_info * dbgi, ir_node * block, ir_node * irn_left, ir_node * irn_right)
Construct a Shl node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_left left
irn_right right
Definition at line 2326 of file gen_irnode.c.
References get_irn_irg(), get_irn_mode(), new_ir_node(), op_Shl, optimize_node(), and verify_new_node().
Referenced by new_d_Shl(), and new_r_Shl().
ir_node* new_Shl (ir_node * irn_left, ir_node * irn_right)
Construct a Shl node.
Parameters
irn_left left
irn_right right
Definition at line 2354 of file gen_irnode.c.
References new_d_Shl().
void set_Shl_left (ir_node * node, ir_node * left)
Sets left input of a Shl node.
Definition at line 2364 of file gen_irnode.c.
void set_Shl_right (ir_node * node, ir_node * right)
Sets right input of a Shl node.
Definition at line 2374 of file gen_irnode.c.
Variable Documentation
ir_op* op_Shl
Shl opcode.
Definition at line 3468 of file nodes.h.
Referenced by get_op_Shl(), and new_rd_Shl().